### ISSUE TITLE
Munki 4

### ISSUE THREAD

**Issue by froggtech** [waderobson/gcs-auth#3]
I'm testing out Munki 4 right now, and the middleware for Google Cloud is failing. Can you update the modules for python3 along with documentation? I'm working on my python skills, but thus far, keep having munki error out. Any ideas or help would be great.

Thanks.

**Comment by waderobson** [comment]
Thanks for the issue. I'll sort this out and get back to you.

**Comment by nielshojen** [comment]
just for good measure, this is the error it's throwing:

> WARNING: Ignoring /usr/local/munki/middleware_gcs.py because of error importing module.

Like @froggtech I'm not that skilled in python, but I'll gladly look into it.

Looks like these aren't a part of the python included with munki 4

`
from OpenSSL.crypto import FILETYPE_PEM
from OpenSSL.crypto import load_privatekey
from OpenSSL.crypto import sign

from urlparse import urlparse
from urllib import quote_plus
`

**Comment by jonbrown21** [comment]
I was able to fix the errors and added Python 2 / 3 compatibility as you can see here which passes and allows managedsoftwareupdate to run. See gist https://gist.github.com/jonbrown21/2828a3c199afc784681f04ba10e26c67

However when I run managedsoftwareupdate with this I get 

`b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>MalformedSecurityHeader</Code><Message>Your request has a malformed header.</Message><ParameterName>signature</ParameterName><Details>Signature was not base64 encoded</Details></Error>"`

hopefully this gets you a little closer?

**Comment by jonbrown21** [comment]
Nevermind figured it out, looks like it was adding an extra character will push working code here shortly.

**Comment by waderobson** [comment]
Thanks @jonbrown21 and @nielshojen for your help on this. I was working on this myself and missed the decode on the signature. I've merged #6 with support for munki 4
